cargo-features = ["per-package-target"]

[package]
name = "at32f403acgu7_experiment"
edition = "2021"
version = "0.1.0"
publish = false
forced-target = "thumbv7em-none-eabihf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
